from dataclasses import dataclass
from typing import Dict, List, Any


@dataclass
class Episode:
    """Store all relevant information of a fact-checking episode.
    
    Attributes:
        text: The complete response text from the model
        generated_token_ids: List of token IDs generated by the model
        is_finished: Whether the generation completed successfully
        reward: Combined reward (format + answer rewards)
        reward_info: Dictionary containing format_reward and answer_reward
        conversation: List of conversation messages in DeepSeek VL2 format
        images: List of image paths used in this episode
    """

    text: str
    generated_token_ids: List[int]
    is_finished: bool
    reward: float
    reward_info: Dict[str, float]
    conversation: List[Dict[str, Any]]
    images: List[str]


@dataclass
class MiniBatch:
    """Batch of data for each training step."""

    inputs: List[Dict[str, Any]]  # Processed inputs from DeepSeek VL2 processor
    conversations: List[List[Dict[str, Any]]]  # List of conversation histories
    images: List[List[str]]  # List of image paths for each sample
    targets: List[str]  # Ground truth labels for fact-checking
